# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', help_text='This is used to build the URL for this page', max_length=250, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='complete_slug',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='internal field to build the full path URL', max_length=255, verbose_name='complete slug'),
        ),
    ]
