# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20161203_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
    ]
